import { C, FONT, FINDINGS } from '../constants'
import finalLogo from '@/assets/final_logo.png'

export default function PdfModal({ target, onClose }: { target: string; onClose: () => void }) {
  return (
    <div
      onClick={e => e.target === e.currentTarget && onClose()}
      role="dialog"
      aria-modal="true"
      aria-label="Report preview"
      style={{
        position: 'fixed', inset: 0, zIndex: 200,
        background: 'rgba(10,10,15,0.85)', backdropFilter: 'blur(4px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
      }}
    >
      <div className="pdf-modal-enter" style={{
        width: 960, maxHeight: '90vh', background: C.bgSecondary,
        border: `1px solid ${C.border}`, borderRadius: 12,
        display: 'flex', flexDirection: 'column', overflow: 'hidden',
      }}>
        <div style={{
          height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '0 24px', borderBottom: `1px solid ${C.border}`, flexShrink: 0,
        }}>
          <span style={{ fontFamily: FONT.grotesk, fontWeight: 600, fontSize: 13, color: C.textPrimary }}>REPORT PREVIEW</span>
          <span style={{ fontFamily: FONT.inter, fontSize: 12, color: C.muted }}>0xVerdict Assessment Report</span>
          <button
            onClick={onClose}
            aria-label="Close preview"
            style={{
              background: 'transparent', border: 'none', cursor: 'pointer',
              fontFamily: FONT.inter, fontSize: 13, color: C.muted,
              display: 'flex', alignItems: 'center', gap: 6,
              transition: 'color 150ms',
            }}
            onMouseEnter={e => (e.currentTarget.style.color = C.red)}
            onMouseLeave={e => (e.currentTarget.style.color = C.muted)}
          >
            &#x2715; Close
          </button>
        </div>

        <div style={{ flex: 1, overflowY: 'auto', background: '#e8e8e8', padding: 32 }}>
          <div style={{
            width: '100%', maxWidth: 794, margin: '0 auto',
            background: '#fff', boxShadow: '0 4px 40px rgba(0,0,0,0.3)',
            fontFamily: "'Georgia', serif",
          }}>
            <div style={{ background: '#0A0A0F', padding: '48px 56px', minHeight: 480 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 48 }}>
                <img
                  src={finalLogo}
                  alt="0xVerdict"
                  style={{ width: 56, height: 56, objectFit: 'cover', borderRadius: '50%', filter: 'drop-shadow(0 0 12px rgba(0,255,136,0.5))' }}
                />
                <div>
                  <div style={{ fontFamily: FONT.grotesk, fontWeight: 700, fontSize: 28, color: '#fff' }}>
                    <span style={{ color: '#00FF88' }}>0x</span>Verdict
                  </div>
                  <div style={{ fontFamily: FONT.mono, fontSize: 10, color: '#8892A4' }}>AI Security Intelligence Platform</div>
                </div>
              </div>

              <div style={{ fontFamily: FONT.grotesk, fontWeight: 700, fontSize: 22, color: '#F0F0F0', marginBottom: 32, letterSpacing: '0.05em', textTransform: 'uppercase' }}>
                Vulnerability Assessment Report
              </div>

              <table style={{ borderCollapse: 'collapse', width: '100%', marginBottom: 48 }}>
                <tbody>
                  {[
                    ['Target URL', target],
                    ['Scan Date', '2026-07-19'],
                    ['Scan Status', 'Completed'],
                    ['Duration', '45 seconds'],
                    ['Generated By', '0xVerdict AI Engine v1.0.0'],
                  ].map(([k, v]) => (
                    <tr key={k}>
                      <td style={{ fontFamily: FONT.mono, fontSize: 11, color: '#8892A4', padding: '6px 0', width: 160 }}>{k}:</td>
                      <td style={{ fontFamily: FONT.mono, fontSize: 11, color: '#F0F0F0', padding: '6px 0' }}>{v}</td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 2 }}>
                {[
                  { label: 'CRITICAL', count: 1, color: '#FF3366' },
                  { label: 'HIGH', count: 2, color: '#FFB800' },
                  { label: 'MEDIUM', count: 3, color: '#7B61FF' },
                  { label: 'LOW', count: 1, color: '#8892A4' },
                ].map(s => (
                  <div key={s.label} style={{ background: s.color, padding: '10px 16px' }}>
                    <div style={{ fontFamily: FONT.grotesk, fontWeight: 700, fontSize: 20, color: '#fff' }}>{s.count}</div>
                    <div style={{ fontFamily: FONT.grotesk, fontSize: 10, color: 'rgba(255,255,255,0.8)', letterSpacing: '0.1em' }}>{s.label}</div>
                  </div>
                ))}
              </div>
            </div>

            <div style={{ padding: '48px 56px', borderBottom: '1px solid #ddd' }}>
              <h1 style={{ fontFamily: "'Georgia', serif", fontSize: 24, color: '#111', marginBottom: 16, fontWeight: 700 }}>Executive Summary</h1>
              <p style={{ fontFamily: FONT.inter, fontSize: 14, color: '#444', lineHeight: 1.7, marginBottom: 24 }}>
                An automated vulnerability assessment was conducted against <strong>{target}</strong> on 2026-07-19. The scan identified <strong>5 potential security issues</strong>, of which <strong>3 were confirmed</strong> by the AI Verdict Engine, <strong>1 requires manual verification</strong>, and <strong>1 was classified as a likely false positive</strong>. Immediate remediation is recommended for the confirmed SQL Injection vulnerability due to potential database compromise risk.
              </p>
            </div>

            {FINDINGS.filter(f => f.verdict === 'confirmed').map(f => (
              <div key={f.id} style={{ padding: '40px 56px', borderBottom: '1px solid #ddd' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
                  <div>
                    <div style={{ fontFamily: FONT.mono, fontSize: 11, color: '#888', marginBottom: 4 }}>{f.id}</div>
                    <h2 style={{ fontFamily: "'Georgia', serif", fontSize: 20, color: '#111', fontWeight: 700 }}>{f.type}</h2>
                  </div>
                  <div style={{ textAlign: 'right', fontFamily: FONT.inter, fontSize: 12, color: '#555' }}>
                    <div>Endpoint: <strong style={{ fontFamily: FONT.mono }}>{f.endpoint}</strong></div>
                    <div>AI Verdict: <strong style={{ color: '#00AA55' }}>{'\u2705'} CONFIRMED</strong></div>
                  </div>
                </div>

                <div style={{ background: '#fff8f8', border: '1px solid #ffcccc', borderRadius: 4, padding: '8px 14px', marginBottom: 16, fontFamily: FONT.inter, fontSize: 12, color: '#cc3333' }}>
                  Scanner Severity: <s>{f.scannerSeverity}</s> {'\u2192'} AI Classified: <strong>{f.aiSeverity}</strong>
                </div>

                {[
                  { label: 'Root Cause', text: f.rootCause },
                  { label: 'Developer Explanation', text: f.devExplanation },
                  { label: 'Fix Recommendation', text: f.fixRecommendation },
                ].map(({ label, text }) => (
                  <div key={label} style={{ marginBottom: 14 }}>
                    <h3 style={{ fontFamily: FONT.inter, fontWeight: 600, fontSize: 13, color: '#333', marginBottom: 4 }}>{label}</h3>
                    <p style={{ fontFamily: FONT.inter, fontSize: 13, color: '#555', lineHeight: 1.6 }}>{text}</p>
                  </div>
                ))}

                <div style={{ marginBottom: 14 }}>
                  <h3 style={{ fontFamily: FONT.inter, fontWeight: 600, fontSize: 13, color: '#333', marginBottom: 8 }}>Secure Code Example (Node.js)</h3>
                  <pre style={{
                    background: '#1a1a2e', color: '#00FF88', fontFamily: FONT.mono, fontSize: 12,
                    padding: '16px', borderRadius: 4, overflow: 'auto', lineHeight: 1.6,
                  }}>{f.remediationCode}</pre>
                </div>
              </div>
            ))}

            <div style={{ padding: '24px 56px', background: '#f9f9f9' }}>
              <p style={{ fontFamily: FONT.inter, fontSize: 11, color: '#888', lineHeight: 1.6 }}>
                NOTICE: This tool is intended exclusively for authorized security testing environments (e.g., OWASP Juice Shop, DVWA, or infrastructure where explicit written permission has been granted). Unauthorized scanning violates global cyber defense frameworks. Authors assume no liability for misuse.
              </p>
            </div>
          </div>
        </div>

        <div style={{
          height: 60, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 12,
          borderTop: `1px solid ${C.border}`, padding: '0 24px', flexShrink: 0,
        }}>
          <button style={{
            height: 40, padding: '0 20px', borderRadius: 6, border: 'none', cursor: 'pointer',
            background: C.green, color: C.bgPrimary, fontFamily: FONT.grotesk, fontWeight: 600, fontSize: 13,
            display: 'flex', alignItems: 'center', gap: 6,
          }}>{'\uD83D\uDCE5'} Download PDF</button>
          <button style={{
            height: 40, padding: '0 20px', borderRadius: 6, cursor: 'pointer',
            background: 'transparent', border: `1px solid ${C.border}`,
            color: C.textPrimary, fontFamily: FONT.grotesk, fontSize: 13,
            display: 'flex', alignItems: 'center', gap: 6,
          }}>{'\uD83D\uDCDD'} Download Markdown</button>
          <button
            onClick={onClose}
            style={{
              height: 40, padding: '0 20px', borderRadius: 6, cursor: 'pointer',
              background: 'transparent', border: `1px solid ${C.border}`,
              color: C.muted, fontFamily: FONT.grotesk, fontSize: 13,
            }}
          >{'\u2715'} Close Preview</button>
        </div>
      </div>
    </div>
  )
}
